
name: Storybook deploy to gh-pages
on:
  push:
    branches:
      - dev 
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build storybook static files
        run: |
          npm ci
          npm run build-storybook
      - name: Create _pass.txt file
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: echo "index.html pass" > _pass.txt
      - name: Encrypt pages with PageCrypt
        run: |
          npm i -D pagecrypt
          cat pass.txt | while read file password;
          do
            sudo npx pagecrypt "$file" "$file" "$password"
          done
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: storybook-hosting
          folder: storybook-static
          commit-message: deploy storybook
