
name: Storybook deploy to gh-pages
on:
  push:
    branches:
      - dev 
permissions:
  contents: read
  pages: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build storybook static files
        run: |
          npm install
          npm run build-storybook
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: storybook-hosting
          folder: storybook-static
